function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(8)=0;
    ys_(6)=1/params(2);
    KtoL=(params(1)/(1/params(2)-(1-params(3))))^(1/(1-params(1)));
    CtoL=KtoL^params(1)-params(3)*KtoL;
    ys_(7)=(1-params(1))*KtoL^params(1);
    ys_(4)=(KtoL^params(1)*(1-params(1))/params(7)/CtoL)^(params(4)/(1+params(4)));
    ys_(3)=KtoL*ys_(4);
    ys_(5)=ys_(3)^params(1)*ys_(4)^(1-params(1));
    ys_(2)=params(3)*ys_(3);
    ys_(1)=ys_(5)-ys_(2);
    % Auxiliary equations
end
